# Generated by Django 3.1.1 on 2020-09-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-date_created'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='balance',
        ),
    ]
